# Example secrets file - DO NOT COMMIT real secrets here.
# Use Streamlit Cloud Secrets UI to set these values in production.

[model_storage]
# Example: a public or signed URL where your model artifacts can be fetched at runtime
# model_url = "https://example.com/path/to/model.joblib"

[aws]
# Example S3 credentials (if you download artifacts from S3 at startup)
# aws_access_key_id = "YOUR_ACCESS_KEY"
# aws_secret_access_key = "YOUR_SECRET_KEY"
# aws_region = "us-east-1"

